import {Component,inject,signal} from '@angular/core';
import {RouterLink,ActivatedRoute,Router} from '@angular/router';
import {FormsModule} from '@angular/forms';
import {IconComponent} from './icon';
import {EnquiryComponent} from './enquiry';
import {MotionDirective} from './motion';
import {services,destinations} from './data';

@Component({selector:'st-home',standalone:true,imports:[RouterLink,FormsModule,IconComponent,EnquiryComponent,MotionDirective],templateUrl:'./home.html'})
export class HomeComponent{
 services=services.slice(0,6);destinations=destinations;router=inject(Router);quickService='chauffeur';pickup='';destination='';date='';
 today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 startEnquiry(){this.router.navigate(['/contact-us'],{queryParams:{service:this.quickService,pickup:this.pickup,destination:this.destination,date:this.date}});}
}
@Component({selector:'st-about',standalone:true,imports:[RouterLink,IconComponent,MotionDirective],template:`
<div stMotion><section class="page-intro container"><p class="eyebrow">ROOTED IN KANYAKUMARI</p><h1>Your journey.<br><span class="highlight">Our priority.</span></h1><p class="intro-copy">A local starting point for the places you want to go.</p></section>
<section class="about-story container"><div class="story-image reveal"><img class="parallax-image" src="/assets/kanyakumari.webp" width="900" height="1000" alt="Vivekananda Rock Memorial off the Kanyakumari coast"></div><div class="story-copy reveal"><h2>From our hometown<br>to your next adventure.</h2><p>Based on Church Road in Kanyakumari, Stellora Travels brings rentals, tours and travel booking assistance together in one place.</p><p>Whether you need a bike for the day, a car with a driver, a self-drive rental or a drop at Trivandrum Airport, start by telling us about your plans.</p><p>We also help with customised tours, wedding transport, college industrial visits, visa assistance, tickets and hotel bookings.</p><a routerLink="/services" class="button secondary">Explore services</a></div></section>
<section class="section soft"><div class="container"><div class="section-heading reveal"><h2>A trip that fits <span>your plans.</span></h2><p>Different journeys call for different ways to travel.</p></div><div class="values-grid"><article class="reveal"><st-icon name="steering-wheel"/><h3>Choose your own pace</h3><p>Self-drive cars, chauffeur-driven trips and bike rentals give you different ways to explore.</p></article><article class="reveal"><st-icon name="map-pin"/><h3>Start locally</h3><p>Visit our Kanyakumari office or send an enquiry for trips around Kanyakumari and Trivandrum.</p></article><article class="reveal"><st-icon name="luggage"/><h3>Bring your plans together</h3><p>Ask about transport, tickets, accommodation and group travel through one point of contact.</p></article></div></div></section>
<section class="visit-section container section"><div class="reveal"><h2>Let's talk travel.</h2><p>Visit us at No. 21, First Floor, behind Indian Bank,<br>Church Road, Kanyakumari 629702.</p><p><strong>Office hours: 5:00 AM to 12:00 noon IST</strong></p><div class="button-row"><a routerLink="/contact-us" class="button primary">Plan my trip</a><a href="https://maps.app.goo.gl/NKSd1zCMPByPvWEq5" target="_blank" rel="noopener" class="text-link">Find our office</a></div></div><img class="reveal" src="/assets/poovar.webp" alt="Palm-lined backwaters at Poovar" width="650" height="450" loading="lazy"></section></div>
`})export class AboutComponent{}
@Component({selector:'st-services',standalone:true,imports:[RouterLink,IconComponent,MotionDirective],template:`
<div stMotion><section class="page-intro container"><p class="eyebrow">THE WAY YOU WANT TO TRAVEL</p><h1>More possibilities.<br><span class="highlight">One travel partner.</span></h1><p class="intro-copy">From your daily ride to a well-earned getaway, find the service that fits.</p></section>
<section class="container services-list"><div class="filter-row" role="group" aria-label="Filter services">@for(cat of categories;track cat){<button [class.selected]="filter()===cat" [attr.aria-pressed]="filter()===cat" (click)="filter.set(cat)">{{cat}}</button>}</div><div class="service-grid">@for(s of filtered();track s.id){<article class="service-detail" [id]="s.id"><div class="service-symbol"><st-icon [name]="s.icon"/></div><span class="service-category">{{s.category}}</span><h2>{{s.name}}</h2><p>{{s.description}}</p><a class="text-link" routerLink="/contact-us" [queryParams]="{service:s.id}">Enquire now</a></article>}</div></section>
<section class="section container"><div class="section-heading"><h2>Good journeys.<br><span>Clear starting prices.</span></h2></div><div class="offers-grid"><article class="offer airport-offer"><div><span>ONE-WAY AIRPORT DROP</span><h3>Kanyakumari to<br>Trivandrum Airport</h3><p class="price">₹3,200</p><p>Parking charges extra.</p><a class="button primary" routerLink="/contact-us" [queryParams]="{service:'airport',pickup:'Kanyakumari',destination:'Trivandrum Airport'}">Enquire now</a></div><img src="/assets/suv.webp" alt="Illustrative white SUV" width="600" height="400" loading="lazy"></article><article class="offer bike-offer"><div><span>BIKE RENTALS</span><h3>A day of<br>your own.</h3><p class="price">₹400–₹500 <small>/ day</small></p><p>100 km included per day.<br>₹5 per additional km.</p><a class="button secondary" routerLink="/contact-us" [queryParams]="{service:'bike'}">Enquire now</a></div><img src="/assets/scooter.webp" alt="Illustrative yellow scooter" width="450" height="400" loading="lazy"></article></div><p class="asset-note">Vehicle imagery is illustrative. Ask us about available vehicles and rental terms.</p></section>
<section class="section soft"><div class="container"><div class="section-heading"><h2>A few places to <span>start.</span></h2><p>Suggested destinations for your customised trip. Enquire for itinerary and pricing.</p></div><div class="destination-grid">@for(d of destinations;track d.name){<a routerLink="/contact-us" [queryParams]="{service:'tours',destination:d.name}" class="destination"><img [src]="'/assets/'+d.image" [alt]="d.name+' destination scenery'" width="500" height="600" loading="lazy"><div><span>{{d.tag}}</span><h3>{{d.name}}</h3><p>Plan a trip</p></div></a>}</div></div></section></div>
`})export class ServicesComponent{services=services;destinations=destinations;categories=['All services','Ride','Explore','Occasions','Travel essentials'];filter=signal('All services');filtered(){return this.services.filter(s=>this.filter()==='All services'||s.category===this.filter());}}
@Component({selector:'st-contact',standalone:true,imports:[EnquiryComponent,IconComponent,MotionDirective],template:`
<div stMotion><section class="page-intro container contact-intro"><p class="eyebrow">LET'S MAKE PLANS</p><h1>Where are we<br><span class="highlight">taking you?</span></h1><p class="intro-copy">A quick ride, a long weekend or something special. Tell us what you have in mind.</p></section>
<section class="container contact-layout"><div class="contact-info"><h2>Every trip starts<br>with a conversation.</h2><a class="contact-method" href="tel:+918939783708"><st-icon name="phone"/><div><span>Call us</span><strong>+91 89397 83708</strong></div></a><a class="contact-method" href="mailto:stelloratravels@gmail.com"><st-icon name="mail"/><div><span>Email us</span><strong>stelloratravels&#64;gmail.com</strong></div></a><div class="contact-method"><st-icon name="clock"/><div><span>Office hours</span><strong>5:00 AM to 12:00 noon IST</strong></div></div><div class="office-box"><st-icon name="map-pin"/><h3>Come say hello.</h3><p>No. 21, First Floor,<br>behind Indian Bank, Church Road,<br>Kanyakumari 629702.</p><a class="text-link" href="https://maps.app.goo.gl/NKSd1zCMPByPvWEq5" target="_blank" rel="noopener">Open Google Maps</a></div></div><st-enquiry [initialService]="service" [initialPickup]="pickup" [initialDestination]="destination" [initialDate]="date"/></section></div>
`})export class ContactComponent{private params=inject(ActivatedRoute).snapshot.queryParamMap;service=services.some(s=>s.id===this.params.get('service'))?this.params.get('service')||'':'';pickup=this.params.get('pickup')||'';destination=this.params.get('destination')||'';date=this.params.get('date')||'';}
@Component({selector:'st-not-found',standalone:true,imports:[RouterLink],template:`<section class="page-intro container"><h1>A little off route.</h1><p>This page isn't here. Let's get you back to your journey.</p><a routerLink="/" class="button primary">Back to home</a></section>`})export class NotFoundComponent{}
